# Generated by Django 6.0.5 on 2026-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('HOUSEKEEPING', 'Housekeeping'), ('RESTAURANT', 'Restaurant'), ('MAINTENANCE', 'Maintenance'), ('ACCOUNTS', 'Accounts'), ('STORE', 'Store'), ('MANAGEMENT', 'Management'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
