# Generated by Django 6.0.5 on 2026-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('HOUSEKEEPING', 'Housekeeping'), ('RESTAURANT', 'Restaurant'), ('BAR', 'Bar'), ('HOUSEKEEPING', 'Housekeeping'), ('FINANCE', 'Finance'), ('SECURITY', 'Security'), ('STORE', 'Store'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
