# Generated by Django 6.0.5 on 2026-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('RESTAURANT', 'Restaurant'), ('ACCOUNTANT', 'Accountant'), ('STORE_MANAGER', 'Store Manager'), ('HOUSE_KEEPER', 'House Keeper'), ('SALES_PERSON', 'Sales Person')], default='RECEPTIONIST', max_length=20),
        ),
    ]
