# Generated by Django 6.0.5 on 2026-05-10 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_guestcharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicerequest',
            name='added_to_guest_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomservicerequest',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Beverage'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry'), ('COMFORT', 'Guest Comfort'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transportation'), ('BUSINESS', 'Business Service'), ('CONCIERGE', 'Concierge'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='FOOD', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomservicerequest',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomservicerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomservicerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='roomservicerequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomservicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomservicerequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
